services:
   server:
    image: pazcalb/run2heaven-server:v1.0.0-arm64
    ports:
      - 3100:3100
    environment:
      - NODE_ENV=production
      - PORT=3100
      - DATABASE_URL=postgres://postgres:1234@postgres:5432/run2heaven
    volumes:
      - ./images:/app/images
    networks:
      - run2heaven-network
   postgres:
     image: postgres
     environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: run2heaven
     volumes:
      - ./postgres-data:/var/lib/postgresql/data
     ports:
       - 5437:5432
     networks:
        - run2heaven-network
networks:
  run2heaven-network:
      